name: Issue Notifier

on:
  issues:
    types: [opened]

permissions:
  issues: read

jobs:
  notify:
    name: "Telegram notification"
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram notification for new issue
        uses: sehat1137/telegram-notifier@5d130037eb80a33251f3afe8bc56447236acab77 # v1.3.0
        with:
          tg-bot-token: ${{ secrets.TELEGRAM_TOKEN }}
          tg-chat-id: ${{ secrets.TELEGRAM_TO }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Send Telegram notification to OSS board
        uses: sehat1137/telegram-notifier@5d130037eb80a33251f3afe8bc56447236acab77 # v1.3.0
        with:
          tg-bot-token: ${{ secrets.TELEGRAM_TOKEN }}
          tg-chat-id: ${{ secrets.GFI_CHAT }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          trigger-labels: "good first issue"
